import Head from 'next/head'
import Image from 'next/image'
import { data } from '../data.js'
import '../styles/globals.css'

export default function Home() {

  type Link = {
    href: string,
    name: string,
  }

  type Social = {
    href: string,
    name: string,
    icon: React.ReactNode
  }

  function LinkCard({ href, name }: Link) {
    return (
      <a href={href} target='_blank' className='flex items-center p-4 rounded-full hover:bg-white hover:text-gray-600 duration-200 transition-all w-full justify-center border border-white mb-3 max-w-2xl text-white'>
        <div className='flex flex-col'>
          <h2 className='font-semibold lg:text-lg'>{name}</h2>
        </div>
      </a>
    )
  }

  function SocialCard({ href, icon }: Social) {
    return (
      <a href={href} target='_blank' className='text-white'>
        <div className='flex'>
          <h2 className='font-semibold text-3xl'>{icon}</h2>
        </div>
      </a>
    )
  }

  return (
    <>
      <Head>
        <title>Link</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen w-full bg-gradient-to-b from-gray-400 to-gray-900'>
        <div className='flex items-center mx-auto w-full justify-center flex-col px-4'>
          <Image className='rounded-full mt-16' src={data.avatar} width={96} height={96} alt={data.avatar} />
          <h1 className='font-bold mt-4 text-xl mb-8 text-white'>{data.name}</h1>
          {data.links.map((link, index) => (
            <LinkCard key={index} {...link} />
          ))}
        </div>
        <div className='flex justify-center mt-6 gap-4'>
          {data.socials.map((social, index) => (
            <SocialCard key={index} {...social} />
          ))}
        </div>
      </div>
    </>
  )
}
